name: Trigger Target Repo Workflow on Dependabot Update

on:
  pull_request:
    types: [open, synchronize, closed]
    branches:
      - main # Branch where Dependabot operates
  # push:
  #   branches:
  #    - main

# Required Permissions by GITHUB_TOKE
permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read
  deployments: write

jobs:
 
  # auto-merge:
  #   # if: ${{ github.actor == 'dependabot[bot]' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Auto Merge Dependabot PRs
  #       run: |
  #         gh pr merge ${{ github.event.pull_request.number }} --merge --admin
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

  notify-target-repo:
    # if: ${{ github.actor == 'dependabot[bot]' }} # Ensure only Dependabot triggers this job
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_SECRET }}
          script: |
            github.rest.repos.createDispatchEvent({
              owner: 'hamzanasir47',  //# Replace with target repo owner
              repo: 'terraform-testing',   //# Replace with target repo name
              event_type: 'dependabot-update-1', //# Matche event type in target repo
              //client_payload: {
              //  updated_file: 'provider.tf',   # Example of passing the updated file
              //}
            })
